sudo: required

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y openssh-client

script:
  - export PATH="$(pwd)/bin:$PATH"
  - docker build -t dumpling dumpling
  - dumpling whoami | grep "$(whoami)"
  - dumpling python -c "import numpy as np; assert np.array([1]) + np.array([1]) == 2"
  - dumpling bash -c 'pip install jenkspy && python -c "import jenkspy"'
