#!/bin/sh

set -eux

# Step 1 - Prepare the dough for the dumpling.
# Install Python development tools, compilers, and build dependencies.
# bzip2, tar, wget are needed to download phantomjs.
# git is needed to download oaglib.
# unixodbc-dev is needed to build pyodbc.
# GDAL depends on specific versions of its C/C++ libraries, so just
# install the Debian package instead of building from source.
apt-get -qq update
apt-get install -qy --no-install-recommends \
   bzip2 \
   g++ \
   gcc \
   git \
   python3-dev \
   python3-gdal \
   python3-pip \
   python3-setuptools \
   python3-wheel \
   tar \
   unixodbc-dev \
   virtualenv \
   wget

# Create a symlink from python/pip to Python 3,
# since we are not using Python 2.
ln -s ../../bin/python3 /usr/local/bin/python
ln -s ../../bin/pip3 /usr/local/bin/pip

# Step 2 - Pack the dumpling with lots of veggies and steam it.
# Install Python packages for data science.
pip3 install --no-cache-dir \
    awscli \
    beautifulsoup4 \
    bokeh \
    civis \
    dash \
    emoji \
    Fiona \
    folium \
    fuzzywuzzy[speedup] \
    geopandas \
    jupyter_contrib_nbextensions \
    line_profiler \
    lxml \
    notebook \
    matplotlib \
    memory_profiler \
    nbdiff \
    neo4j-driver \
    nltk \
    numpy \
    pandas \
    pandas-datareader \
    pdfminer.six \
    Pillow \
    plotly \
    pre-commit \
    probablepeople \
    pyodbc \
    PyPDF2 \
    pyproj \
    requests \
    scikit-image \
    scikit-learn \
    scipy \
    scrapy \
    seaborn \
    selenium \
    shapely \
    six \
    sqlalchemy \
    sqlalchemy-redshift \
    statsmodels \
    tenacity \
    tensorflow \
    tox \
    unidecode \
    xmltodict \
    git+https://github.com/NYAG/oaglib.git

# Install PhantomJS as a Selenium WebDriver.
# TODO: automatically find the latest version of PhantomJS.
# It would be nice to use the Debian package but there are bugs:
# https://bugs.debian.org/cgi-bin/pkgreport.cgi?package=phantomjs
wget --no-hsts -O phantomjs.tar.bz2 \
    https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
tar --wildcards --strip-components=2 -xf phantomjs.tar.bz2 \
    'phantomjs*/bin/phantomjs'
mv phantomjs /usr/local/bin
rm phantomjs.tar.bz2

# Step 3 - Add some dipping sauce to the dumpling.
# Install Debian packages for convenient CLI work.
apt-get install -qy --no-install-recommends \
   bash-completion \
   bc \
   cowsay \
   curl \
   dnsutils \
   ghostscript \
   gosu \
   host \
   htop \
   imagemagick \
   jq \
   less \
   lsof \
   man-db \
   nano \
   net-tools \
   openssh-client \
   p7zip-full \
   postgresql-client \
   procps \
   sl \
   sudo \
   tree \
   vim \
   watch

# Step 4 - Indulge in the dumpling.
# Enable sudo without a password.
echo '%sudo ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/nopasswd

# Modify bashrc to enable bash-completion and other savories.
# Enable git pull rebase autostash.
echo '. /srv/bashrc' >> /etc/bash.bashrc
echo '. /srv/bash_logout' >> /etc/bash.bash.logout
ln -s /srv/gitconfig /etc/gitconfig

# Step 5 - Clean the dishes.
apt-get clean
rm -rf /var/lib/apt/lists/*
