#!/bin/sh

set -eux

# Step 1 - Prepare the dough for the dumpling.
# Install Python development tools, compilers, and build dependencies.
# bzip2, tar, wget are needed to download phantomjs.
# git is needed to download oaglib.
# graphviz is needed for dask.dataframe.DataFrame.visualize
# unixodbc-dev is needed to build pyodbc.
# GDAL depends on specific versions of its C/C++ libraries, so just
# install the Debian package instead of building from source.
apt-get -qq update
apt-get install -qy --no-install-recommends \
   bzip2 \
   g++ \
   gcc \
   git \
   graphviz \
   python3-dev \
   python3-gdal \
   python3-pip \
   python3-setuptools \
   python3-wheel \
   tar \
   unixodbc-dev \
   virtualenv \
   wget

# Create a symlink from python/pip to Python 3,
# since we are not using Python 2.
ln -s ../../bin/python3 /usr/local/bin/python
ln -s ../../bin/pip3 /usr/local/bin/pip

# Step 2 - Pack the dumpling with lots of veggies and steam it.
# Install Python packages for data science.
# Cython needs to be installed first for fastparquet, used by dask.
# We can remove fastparquet once dask fully supports pyarrow.
pip3 install --no-cache-dir cython
pip3 install --no-cache-dir --upgrade \
    awscli \
    beautifulsoup4 \
    bokeh \
    boto3 \
    cachey \
    civis \
    csvkit \
    'dask[complete]' \
    dask-searchcv \
    dedupe \
    dedupe-variable-address \
    dedupe-variable-name \
    emoji \
    fastparquet \
    Fiona \
    folium \
    'fuzzywuzzy[speedup]' \
    geopandas \
    graphviz \
    jupyterlab \
    jupyter_contrib_nbextensions \
    line_profiler \
    lxml \
    notebook \
    matplotlib \
    memory_profiler \
    nbdiff \
    neo4j-driver \
    nltk \
    numpy \
    pandas \
    pandas-datareader \
    pdfminer.six \
    Pillow \
    plotly \
    pre-commit \
    probablepeople \
    pyarrow \
    pyodbc \
    PyPDF2 \
    pyproj \
    requests \
    s3fs \
    scikit-image \
    scikit-learn \
    scipy \
    scrapy \
    seaborn \
    selenium \
    shapely \
    six \
    sqlalchemy \
    sqlalchemy-redshift \
    statsmodels \
    tenacity \
    tensorflow \
    tox \
    ujson \
    unidecode \
    xlrd \
    xmltodict \
    git+https://github.com/NYAG/oaglib.git

# Install PhantomJS as a Selenium WebDriver.
# TODO: automatically find the latest version of PhantomJS.
# It would be nice to use the Debian package but there are bugs:
# https://bugs.debian.org/cgi-bin/pkgreport.cgi?package=phantomjs
wget --no-verbose --no-hsts -O phantomjs.tar.bz2 \
    https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
tar --wildcards --strip-components=2 -xf phantomjs.tar.bz2 \
    'phantomjs*/bin/phantomjs'
mv phantomjs /usr/local/bin
rm phantomjs.tar.bz2

# Step 3 - Add some dipping sauce to the dumpling.
# Install Debian packages for convenient CLI work.
# bash-completion, cowsay, fortune* are used in bashrc.
# cifs-utils, gosu are used in docker-entrypoint.
# locales is needed to support UTF-8 locale, which is required by tmux.
apt-get install -qy --no-install-recommends \
   bash-completion \
   bc \
   cifs-utils \
   cowsay \
   curl \
   dnsutils \
   fortune-mod \
   fortunes \
   fortunes-bofh-excuses \
   ghostscript \
   gosu \
   host \
   htop \
   imagemagick \
   jq \
   less \
   locales \
   lsof \
   man-db \
   nano \
   net-tools \
   openssh-client \
   p7zip-full \
   postgresql-client \
   procps \
   shellcheck \
   sl \
   sudo \
   tree \
   tmux \
   unzip \
   vim \
   watch

# Step 4 - Indulge in the dumpling.
# Enable sudo without a password.
echo '%sudo ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/nopasswd

# Modify bashrc to enable bash-completion and other savories.
# Enable git pull rebase autostash.
# Configure Jupyter Notebook port.
echo '. /srv/bashrc' >> /etc/bash.bashrc
echo '. /srv/bash_logout' >> /etc/bash.bash.logout
ln -s /srv/gitconfig /etc/.
mkdir /etc/jupyter
ln -s /srv/jupyter_notebook_config.py /etc/jupyter/.

# Default to UTF-8 locale.
echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen
locale-gen
update-locale LANG=en_US.UTF-8

# Step 5 - Clean the dishes.
apt-get clean
rm -rf /var/lib/apt/lists/*
